---
api_port: 6443  # noqa var-naming[no-role-prefix]
kubeconfig: ~/.kube/config.new  # noqa var-naming[no-role-prefix]
cluster_context: k3s-ansible  # noqa var-naming[no-role-prefix]
server_group: server  # noqa var-naming[no-role-prefix]
